// AUTO-GENERATED by generate-map.mjs from asi-category-tree.json.
// Edit GROUPS / TOP_TO_GROUP in the generator and re-run; do not hand-edit.
import type { CuratedNode, SourceMap } from './category-map.types';

/** Curated slugs to create even with no mapping (empty leaves). */
export const ALWAYS_CREATE: string[] = ["bestsellers"];

export const curatedTree: CuratedNode[] = [
  {
    "slug": "bestsellers",
    "name": "Best Sellers"
  },
  {
    "slug": "pens",
    "name": "Pens",
    "children": [
      {
        "slug": "cat-pens",
        "name": "Pens",
        "children": [
          {
            "slug": "sub-pens-ballpoint-plunger-action",
            "name": "Ballpoint-Plunger Action"
          },
          {
            "slug": "sub-pens-ballpoint-stylus",
            "name": "Ballpoint-Stylus"
          },
          {
            "slug": "sub-pens-ballpoint-with-grip-section",
            "name": "Ballpoint-With Grip Section"
          },
          {
            "slug": "sub-pens-ballpoint-twist-action",
            "name": "Ballpoint-Twist Action"
          },
          {
            "slug": "sub-pens-general",
            "name": "General"
          },
          {
            "slug": "sub-pens-ballpoint-general",
            "name": "Ballpoint-General"
          },
          {
            "slug": "sub-pens-ballpoint-roller-ball",
            "name": "Ballpoint-Roller Ball"
          },
          {
            "slug": "sub-pens-ballpoint-gel-ink",
            "name": "Ballpoint-Gel Ink"
          },
          {
            "slug": "sub-pens-ballpoint-transparent-barrel-or-cap",
            "name": "Ballpoint-Transparent Barrel or Cap"
          },
          {
            "slug": "sub-pens-ballpoint-with-light",
            "name": "Ballpoint-With Light"
          },
          {
            "slug": "sub-pens-ballpoint-with-highlighter",
            "name": "Ballpoint-With Highlighter"
          },
          {
            "slug": "sub-pens-ballpoint-suede-or-matte-finish",
            "name": "Ballpoint-Suede or Matte Finish"
          },
          {
            "slug": "sub-pens-ballpoint-wide-body",
            "name": "Ballpoint-Wide Body"
          },
          {
            "slug": "sub-pens-ballpoint-clip-action",
            "name": "Ballpoint-Clip Action"
          },
          {
            "slug": "sub-pens-ballpoint-lacquered-finish",
            "name": "Ballpoint-Lacquered Finish"
          },
          {
            "slug": "sub-pens-ballpoint-multi-color",
            "name": "Ballpoint-Multi-Color"
          },
          {
            "slug": "sub-pens-ballpoint-stick",
            "name": "Ballpoint-Stick"
          },
          {
            "slug": "sub-pens-fountain",
            "name": "Fountain"
          },
          {
            "slug": "sub-pens-ballpoint-cap-action",
            "name": "Ballpoint-Cap Action"
          },
          {
            "slug": "sub-pens-ballpoint-triangular",
            "name": "Ballpoint-Triangular"
          },
          {
            "slug": "sub-pens-ballpoint-with-neck-chain-rope",
            "name": "Ballpoint-With Neck Chain/Rope"
          }
        ]
      }
    ]
  },
  {
    "slug": "drinkware",
    "name": "Drinkware",
    "children": [
      {
        "slug": "cat-glasses-drinking",
        "name": "Glassware",
        "children": [
          {
            "slug": "sub-glasses-drinking-sets",
            "name": "Sets"
          },
          {
            "slug": "sub-glasses-drinking-insulated",
            "name": "Insulated"
          },
          {
            "slug": "sub-glasses-drinking-tumbler",
            "name": "Tumbler"
          },
          {
            "slug": "sub-glasses-drinking-with-lid-straw",
            "name": "With Lid & Straw"
          },
          {
            "slug": "sub-glasses-drinking-on-the-rocks",
            "name": "On The Rocks"
          },
          {
            "slug": "sub-glasses-drinking-general",
            "name": "General"
          },
          {
            "slug": "sub-glasses-drinking-champagne",
            "name": "Champagne"
          },
          {
            "slug": "sub-glasses-drinking-pilsner",
            "name": "Pilsner"
          },
          {
            "slug": "sub-glasses-drinking-highball",
            "name": "Highball"
          },
          {
            "slug": "sub-glasses-drinking-margarita",
            "name": "Margarita"
          },
          {
            "slug": "sub-glasses-drinking-beer-jars",
            "name": "Beer Jars"
          },
          {
            "slug": "sub-glasses-drinking-old-fashioned",
            "name": "Old Fashioned"
          },
          {
            "slug": "sub-glasses-drinking-martini",
            "name": "Martini"
          },
          {
            "slug": "sub-glasses-drinking-goblets",
            "name": "Goblets"
          },
          {
            "slug": "sub-glasses-drinking-hurricane",
            "name": "Hurricane"
          },
          {
            "slug": "sub-glasses-drinking-lighted",
            "name": "Lighted"
          }
        ]
      },
      {
        "slug": "cat-bar-accessories",
        "name": "Bar Accessories"
      },
      {
        "slug": "cat-bottles",
        "name": "Water Bottles",
        "children": [
          {
            "slug": "sub-bottles-insulated",
            "name": "Insulated"
          },
          {
            "slug": "sub-bottles-sport-type",
            "name": "Sport Type"
          },
          {
            "slug": "sub-bottles-general",
            "name": "General"
          },
          {
            "slug": "sub-bottles-collapsible",
            "name": "Collapsible"
          },
          {
            "slug": "sub-bottles-spray",
            "name": "Spray"
          },
          {
            "slug": "sub-bottles-baby",
            "name": "Baby"
          }
        ]
      },
      {
        "slug": "cat-travel-mugs-cups",
        "name": "Travel Mugs & Cups"
      },
      {
        "slug": "cat-mugs-steins",
        "name": "Mugs",
        "children": [
          {
            "slug": "sub-mugs-steins-ceramic",
            "name": "Ceramic"
          },
          {
            "slug": "sub-mugs-steins-insulated",
            "name": "Insulated"
          },
          {
            "slug": "sub-mugs-steins-metal",
            "name": "Metal"
          },
          {
            "slug": "sub-mugs-steins-glass",
            "name": "Glass"
          },
          {
            "slug": "sub-mugs-steins-general",
            "name": "General"
          },
          {
            "slug": "sub-mugs-steins-plastic",
            "name": "Plastic"
          },
          {
            "slug": "sub-mugs-steins-porcelain",
            "name": "Porcelain"
          },
          {
            "slug": "sub-mugs-steins-aluminum",
            "name": "Aluminum"
          },
          {
            "slug": "sub-mugs-steins-irish-coffee",
            "name": "Irish Coffee"
          },
          {
            "slug": "sub-mugs-steins-soup-type",
            "name": "Soup Type"
          }
        ]
      },
      {
        "slug": "cat-wine-accessories",
        "name": "Wine Accessories"
      },
      {
        "slug": "cat-openers",
        "name": "Bottle Openers",
        "children": [
          {
            "slug": "sub-openers-bottle",
            "name": "Bottle"
          },
          {
            "slug": "sub-openers-can",
            "name": "Can"
          },
          {
            "slug": "sub-openers-general",
            "name": "General"
          },
          {
            "slug": "sub-openers-touchless",
            "name": "Touchless"
          },
          {
            "slug": "sub-openers-jar",
            "name": "Jar"
          }
        ]
      },
      {
        "slug": "cat-beverage-holders",
        "name": "Can Coolers & Koozies",
        "children": [
          {
            "slug": "sub-beverage-holders-sleeve",
            "name": "Sleeve"
          },
          {
            "slug": "sub-beverage-holders-general",
            "name": "General"
          },
          {
            "slug": "sub-beverage-holders-wrap-around",
            "name": "Wrap Around"
          }
        ]
      },
      {
        "slug": "cat-coasters-coaster-sets",
        "name": "Coasters"
      }
    ]
  },
  {
    "slug": "bags-totes",
    "name": "Bags & Totes",
    "children": [
      {
        "slug": "cat-bags",
        "name": "Bags",
        "children": [
          {
            "slug": "sub-bags-general",
            "name": "General"
          },
          {
            "slug": "sub-bags-drawstring",
            "name": "Drawstring"
          },
          {
            "slug": "sub-bags-shopping",
            "name": "Shopping"
          },
          {
            "slug": "sub-bags-lunch",
            "name": "Lunch"
          },
          {
            "slug": "sub-bags-fanny-hip-waist",
            "name": "Fanny/Hip/Waist"
          },
          {
            "slug": "sub-bags-bottle",
            "name": "Bottle"
          },
          {
            "slug": "sub-bags-crossbody-and-sling",
            "name": "Crossbody and Sling"
          },
          {
            "slug": "sub-bags-food",
            "name": "Food"
          },
          {
            "slug": "sub-bags-shoe",
            "name": "Shoe"
          },
          {
            "slug": "sub-bags-resealable-reclosable",
            "name": "Resealable/Reclosable"
          },
          {
            "slug": "sub-bags-laundry",
            "name": "Laundry"
          },
          {
            "slug": "sub-bags-leather",
            "name": "Leather"
          },
          {
            "slug": "sub-bags-litter",
            "name": "Litter"
          },
          {
            "slug": "sub-bags-diaper",
            "name": "Diaper"
          }
        ]
      },
      {
        "slug": "cat-tote-bags",
        "name": "Tote Bags",
        "children": [
          {
            "slug": "sub-tote-bags-general",
            "name": "General"
          },
          {
            "slug": "sub-tote-bags-non-woven",
            "name": "Non Woven"
          },
          {
            "slug": "sub-tote-bags-canvas",
            "name": "Canvas"
          },
          {
            "slug": "sub-tote-bags-grocery",
            "name": "Grocery"
          },
          {
            "slug": "sub-tote-bags-insulated",
            "name": "Insulated"
          },
          {
            "slug": "sub-tote-bags-jute",
            "name": "Jute"
          },
          {
            "slug": "sub-tote-bags-beach",
            "name": "Beach"
          },
          {
            "slug": "sub-tote-bags-boat",
            "name": "Boat"
          }
        ]
      },
      {
        "slug": "cat-backpacks",
        "name": "Backpacks",
        "children": [
          {
            "slug": "sub-backpacks-general",
            "name": "General"
          },
          {
            "slug": "sub-backpacks-laptop",
            "name": "Laptop"
          },
          {
            "slug": "sub-backpacks-drawstring",
            "name": "Drawstring"
          },
          {
            "slug": "sub-backpacks-school",
            "name": "School"
          }
        ]
      },
      {
        "slug": "cat-coolers",
        "name": "Cooler Bags"
      },
      {
        "slug": "cat-pouches",
        "name": "Pouches",
        "children": [
          {
            "slug": "sub-pouches-general",
            "name": "General"
          },
          {
            "slug": "sub-pouches-jewelry",
            "name": "Jewelry"
          }
        ]
      }
    ]
  },
  {
    "slug": "apparel",
    "name": "Apparel",
    "children": [
      {
        "slug": "cat-performance-apparel",
        "name": "Performance Apparel"
      },
      {
        "slug": "cat-caps-hats",
        "name": "Caps, Hats & Beanies",
        "children": [
          {
            "slug": "sub-caps-hats-general",
            "name": "General"
          },
          {
            "slug": "sub-caps-hats-beanie",
            "name": "Beanie"
          },
          {
            "slug": "sub-caps-hats-golf-general",
            "name": "Golf-General"
          },
          {
            "slug": "sub-caps-hats-visors",
            "name": "Visors"
          },
          {
            "slug": "sub-caps-hats-aussie",
            "name": "Aussie"
          },
          {
            "slug": "sub-caps-hats-santa",
            "name": "Santa"
          },
          {
            "slug": "sub-caps-hats-straw",
            "name": "Straw"
          },
          {
            "slug": "sub-caps-hats-construction",
            "name": "Construction"
          },
          {
            "slug": "sub-caps-hats-with-ear-protection",
            "name": "With Ear Protection"
          },
          {
            "slug": "sub-caps-hats-swimming",
            "name": "Swimming"
          },
          {
            "slug": "sub-caps-hats-fedora",
            "name": "Fedora"
          },
          {
            "slug": "sub-caps-hats-chef-s",
            "name": "Chef's"
          },
          {
            "slug": "sub-caps-hats-sombrero",
            "name": "Sombrero"
          },
          {
            "slug": "sub-caps-hats-derby",
            "name": "Derby"
          },
          {
            "slug": "sub-caps-hats-yarmulkas",
            "name": "Yarmulkas"
          }
        ]
      },
      {
        "slug": "cat-jackets",
        "name": "Jackets",
        "children": [
          {
            "slug": "sub-jackets-general",
            "name": "General"
          },
          {
            "slug": "sub-jackets-pullover",
            "name": "Pullover"
          },
          {
            "slug": "sub-jackets-windbreaker",
            "name": "Windbreaker"
          },
          {
            "slug": "sub-jackets-work",
            "name": "Work"
          },
          {
            "slug": "sub-jackets-parka",
            "name": "Parka"
          },
          {
            "slug": "sub-jackets-in-pouch",
            "name": "In Pouch"
          },
          {
            "slug": "sub-jackets-bomber",
            "name": "Bomber"
          },
          {
            "slug": "sub-jackets-blazer",
            "name": "Blazer"
          },
          {
            "slug": "sub-jackets-varsity-letterman",
            "name": "Varsity/Letterman"
          },
          {
            "slug": "sub-jackets-baseball-coach",
            "name": "Baseball/Coach"
          }
        ]
      },
      {
        "slug": "cat-t-shirts",
        "name": "T-Shirts",
        "children": [
          {
            "slug": "sub-t-shirts-unisex",
            "name": "Unisex"
          },
          {
            "slug": "sub-t-shirts-womens",
            "name": "Womens"
          },
          {
            "slug": "sub-t-shirts-mens",
            "name": "Mens"
          },
          {
            "slug": "sub-t-shirts-children",
            "name": "Children"
          }
        ]
      },
      {
        "slug": "cat-golf-polo-shirts",
        "name": "Polo Shirts",
        "children": [
          {
            "slug": "sub-golf-polo-shirts-mens",
            "name": "Mens"
          },
          {
            "slug": "sub-golf-polo-shirts-womens",
            "name": "Womens"
          },
          {
            "slug": "sub-golf-polo-shirts-unisex",
            "name": "Unisex"
          },
          {
            "slug": "sub-golf-polo-shirts-childrens",
            "name": "Childrens"
          }
        ]
      },
      {
        "slug": "cat-shirts",
        "name": "Shirts",
        "children": [
          {
            "slug": "sub-shirts-womens",
            "name": "Womens"
          },
          {
            "slug": "sub-shirts-tank-tops-muscle",
            "name": "Tank Tops/Muscle"
          },
          {
            "slug": "sub-shirts-unisex",
            "name": "Unisex"
          },
          {
            "slug": "sub-shirts-mens",
            "name": "Mens"
          },
          {
            "slug": "sub-shirts-athletic",
            "name": "Athletic"
          },
          {
            "slug": "sub-shirts-dress",
            "name": "Dress"
          },
          {
            "slug": "sub-shirts-childrens",
            "name": "Childrens"
          },
          {
            "slug": "sub-shirts-general",
            "name": "General"
          },
          {
            "slug": "sub-shirts-henley",
            "name": "Henley"
          },
          {
            "slug": "sub-shirts-camp",
            "name": "Camp"
          },
          {
            "slug": "sub-shirts-denim",
            "name": "Denim"
          },
          {
            "slug": "sub-shirts-wind-shirts",
            "name": "Wind Shirts"
          },
          {
            "slug": "sub-shirts-turtleneck",
            "name": "Turtleneck"
          }
        ]
      },
      {
        "slug": "cat-sweat-shirts",
        "name": "Sweatshirts",
        "children": [
          {
            "slug": "sub-sweat-shirts-unisex",
            "name": "Unisex"
          },
          {
            "slug": "sub-sweat-shirts-womens",
            "name": "Womens"
          },
          {
            "slug": "sub-sweat-shirts-mens",
            "name": "Mens"
          },
          {
            "slug": "sub-sweat-shirts-children",
            "name": "Children"
          }
        ]
      },
      {
        "slug": "cat-baseball-caps",
        "name": "Baseball Caps",
        "children": [
          {
            "slug": "sub-baseball-caps-six-panel",
            "name": "Six Panel"
          },
          {
            "slug": "sub-baseball-caps-with-mesh",
            "name": "with Mesh"
          },
          {
            "slug": "sub-baseball-caps-general",
            "name": "General"
          },
          {
            "slug": "sub-baseball-caps-five-panels",
            "name": "Five Panels"
          },
          {
            "slug": "sub-baseball-caps-camouflage",
            "name": "Camouflage"
          },
          {
            "slug": "sub-baseball-caps-sandwich-bill",
            "name": "Sandwich Bill"
          }
        ]
      },
      {
        "slug": "cat-uniforms",
        "name": "Uniforms",
        "children": [
          {
            "slug": "sub-uniforms-sports",
            "name": "Sports"
          },
          {
            "slug": "sub-uniforms-work-clothes",
            "name": "Work Clothes"
          },
          {
            "slug": "sub-uniforms-restaurant-hospitality",
            "name": "Restaurant/Hospitality"
          },
          {
            "slug": "sub-uniforms-general",
            "name": "General"
          },
          {
            "slug": "sub-uniforms-lab-coats",
            "name": "Lab Coats"
          },
          {
            "slug": "sub-uniforms-scrubs",
            "name": "Scrubs"
          }
        ]
      },
      {
        "slug": "cat-sunglasses",
        "name": "Sunglasses"
      }
    ]
  },
  {
    "slug": "office-desk",
    "name": "Office & Desk",
    "children": [
      {
        "slug": "cat-awards",
        "name": "Awards",
        "children": [
          {
            "slug": "sub-awards-corporate",
            "name": "Corporate"
          },
          {
            "slug": "sub-awards-crystal",
            "name": "Crystal"
          },
          {
            "slug": "sub-awards-glass",
            "name": "Glass"
          },
          {
            "slug": "sub-awards-general",
            "name": "General"
          },
          {
            "slug": "sub-awards-acrylic",
            "name": "Acrylic"
          },
          {
            "slug": "sub-awards-sculptures-figurines",
            "name": "Sculptures & Figurines"
          },
          {
            "slug": "sub-awards-recognition-plaques",
            "name": "Recognition Plaques"
          },
          {
            "slug": "sub-awards-sports",
            "name": "Sports"
          },
          {
            "slug": "sub-awards-clocks",
            "name": "Clocks"
          },
          {
            "slug": "sub-awards-stands-bases",
            "name": "Stands & Bases"
          },
          {
            "slug": "sub-awards-trophies",
            "name": "Trophies"
          },
          {
            "slug": "sub-awards-custom",
            "name": "Custom"
          },
          {
            "slug": "sub-awards-loving-cups",
            "name": "Loving Cups"
          },
          {
            "slug": "sub-awards-embedments",
            "name": "Embedments"
          }
        ]
      },
      {
        "slug": "cat-notebooks",
        "name": "Notebooks"
      },
      {
        "slug": "cat-journals-diaries",
        "name": "Journals & Diaries"
      },
      {
        "slug": "cat-calendars",
        "name": "Calendars",
        "children": [
          {
            "slug": "sub-calendars-wall-general",
            "name": "Wall-General"
          },
          {
            "slug": "sub-calendars-art",
            "name": "Art"
          },
          {
            "slug": "sub-calendars-magnetic",
            "name": "Magnetic"
          },
          {
            "slug": "sub-calendars-general",
            "name": "General"
          },
          {
            "slug": "sub-calendars-year-on-a-page",
            "name": "Year On A Page"
          },
          {
            "slug": "sub-calendars-desk-monthly",
            "name": "Desk-Monthly"
          },
          {
            "slug": "sub-calendars-self-adhering",
            "name": "Self-Adhering"
          },
          {
            "slug": "sub-calendars-commercial",
            "name": "Commercial"
          },
          {
            "slug": "sub-calendars-executive",
            "name": "Executive"
          },
          {
            "slug": "sub-calendars-religious",
            "name": "Religious"
          },
          {
            "slug": "sub-calendars-wall-pocketed",
            "name": "Wall-Pocketed"
          },
          {
            "slug": "sub-calendars-daily-date",
            "name": "Daily Date"
          },
          {
            "slug": "sub-calendars-almanac",
            "name": "Almanac"
          },
          {
            "slug": "sub-calendars-custom-made",
            "name": "Custom Made"
          },
          {
            "slug": "sub-calendars-perpetual",
            "name": "Perpetual"
          },
          {
            "slug": "sub-calendars-year-on-a-page-pocket",
            "name": "Year-On-A-Page-Pocket"
          }
        ]
      }
    ]
  },
  {
    "slug": "usb-tech",
    "name": "USB & Tech",
    "children": [
      {
        "slug": "cat-fans",
        "name": "Fans",
        "children": [
          {
            "slug": "sub-fans-general",
            "name": "General"
          },
          {
            "slug": "sub-fans-usb",
            "name": "USB"
          }
        ]
      },
      {
        "slug": "cat-mobile-accessories",
        "name": "Phone & Tablet",
        "children": [
          {
            "slug": "sub-mobile-accessories-stands-holders",
            "name": "Stands & Holders"
          },
          {
            "slug": "sub-mobile-accessories-general",
            "name": "General"
          },
          {
            "slug": "sub-mobile-accessories-cables-cords",
            "name": "Cables & Cords"
          },
          {
            "slug": "sub-mobile-accessories-cell-phone-wallets",
            "name": "Cell Phone Wallets"
          },
          {
            "slug": "sub-mobile-accessories-cell-phone-cases",
            "name": "Cell Phone Cases"
          },
          {
            "slug": "sub-mobile-accessories-selfie-lights",
            "name": "Selfie Lights"
          },
          {
            "slug": "sub-mobile-accessories-selfie-sticks",
            "name": "Selfie Sticks"
          }
        ]
      },
      {
        "slug": "cat-battery-rechargers-adaptors",
        "name": "Chargers & Power Banks",
        "children": [
          {
            "slug": "sub-battery-rechargers-adaptors-power-banks",
            "name": "Power Banks"
          },
          {
            "slug": "sub-battery-rechargers-adaptors-wireless-qi-charger",
            "name": "Wireless QI Charger"
          },
          {
            "slug": "sub-battery-rechargers-adaptors-general",
            "name": "General"
          }
        ]
      },
      {
        "slug": "cat-usb-flash-drives",
        "name": "USB Drives"
      }
    ]
  },
  {
    "slug": "keychains",
    "name": "Keychains",
    "children": [
      {
        "slug": "cat-key-chains",
        "name": "Keychains",
        "children": [
          {
            "slug": "sub-key-chains-general",
            "name": "General"
          },
          {
            "slug": "sub-key-chains-metal",
            "name": "Metal"
          },
          {
            "slug": "sub-key-chains-with-bottle-or-can-opener",
            "name": "With Bottle or Can Opener"
          },
          {
            "slug": "sub-key-chains-with-flashlight-and-or-whistle",
            "name": "With Flashlight and/or Whistle"
          },
          {
            "slug": "sub-key-chains-plastic",
            "name": "Plastic"
          },
          {
            "slug": "sub-key-chains-with-carabiner",
            "name": "With Carabiner"
          },
          {
            "slug": "sub-key-chains-floating",
            "name": "Floating"
          },
          {
            "slug": "sub-key-chains-leather",
            "name": "Leather"
          },
          {
            "slug": "sub-key-chains-with-tools",
            "name": "With Tools"
          },
          {
            "slug": "sub-key-chains-vinyl",
            "name": "Vinyl"
          },
          {
            "slug": "sub-key-chains-flexible-loop",
            "name": "Flexible Loop"
          },
          {
            "slug": "sub-key-chains-stock-or-id",
            "name": "Stock or ID"
          }
        ]
      }
    ]
  },
  {
    "slug": "leisure",
    "name": "Leisure",
    "children": [
      {
        "slug": "cat-golf-accessories",
        "name": "Golf",
        "children": [
          {
            "slug": "sub-golf-accessories-sets",
            "name": "Sets"
          },
          {
            "slug": "sub-golf-accessories-general",
            "name": "General"
          },
          {
            "slug": "sub-golf-accessories-divot-fixer",
            "name": "Divot Fixer"
          },
          {
            "slug": "sub-golf-accessories-ball-markers",
            "name": "Ball Markers"
          },
          {
            "slug": "sub-golf-accessories-gloves",
            "name": "Gloves"
          },
          {
            "slug": "sub-golf-accessories-ditty-bags",
            "name": "Ditty Bags"
          },
          {
            "slug": "sub-golf-accessories-covers-club",
            "name": "Covers-Club"
          },
          {
            "slug": "sub-golf-accessories-bag-tags",
            "name": "Bag Tags"
          },
          {
            "slug": "sub-golf-accessories-club-cleaners",
            "name": "Club Cleaners"
          },
          {
            "slug": "sub-golf-accessories-green-readers-rangefinders",
            "name": "Green Readers & Rangefinders"
          },
          {
            "slug": "sub-golf-accessories-ball-cleaners",
            "name": "Ball Cleaners"
          },
          {
            "slug": "sub-golf-accessories-putting-cups-greens",
            "name": "Putting Cups/Greens"
          },
          {
            "slug": "sub-golf-accessories-covers-bag",
            "name": "Covers-Bag"
          },
          {
            "slug": "sub-golf-accessories-ball-retrievers",
            "name": "Ball Retrievers"
          },
          {
            "slug": "sub-golf-accessories-scoring-devices",
            "name": "Scoring Devices"
          }
        ]
      },
      {
        "slug": "cat-sports-equipment-access",
        "name": "Sports",
        "children": [
          {
            "slug": "sub-sports-equipment-access-general",
            "name": "General"
          },
          {
            "slug": "sub-sports-equipment-access-baseball-softball",
            "name": "Baseball/Softball"
          },
          {
            "slug": "sub-sports-equipment-access-pickleball",
            "name": "Pickleball"
          },
          {
            "slug": "sub-sports-equipment-access-hockey",
            "name": "Hockey"
          },
          {
            "slug": "sub-sports-equipment-access-fishing-hunting",
            "name": "Fishing & Hunting"
          },
          {
            "slug": "sub-sports-equipment-access-tennis",
            "name": "Tennis"
          },
          {
            "slug": "sub-sports-equipment-access-jogging",
            "name": "Jogging"
          },
          {
            "slug": "sub-sports-equipment-access-capsules",
            "name": "Capsules"
          },
          {
            "slug": "sub-sports-equipment-access-skiing",
            "name": "Skiing"
          },
          {
            "slug": "sub-sports-equipment-access-skating",
            "name": "Skating"
          },
          {
            "slug": "sub-sports-equipment-access-weight-lifting",
            "name": "Weight Lifting"
          }
        ]
      },
      {
        "slug": "cat-tools-kitchen",
        "name": "Kitchen Tools",
        "children": [
          {
            "slug": "sub-tools-kitchen-general",
            "name": "General"
          },
          {
            "slug": "sub-tools-kitchen-sets",
            "name": "Sets"
          },
          {
            "slug": "sub-tools-kitchen-spatulas-spreaders",
            "name": "Spatulas/Spreaders"
          },
          {
            "slug": "sub-tools-kitchen-coffee-makers",
            "name": "Coffee Makers"
          },
          {
            "slug": "sub-tools-kitchen-pizza-accessories",
            "name": "Pizza Accessories"
          },
          {
            "slug": "sub-tools-kitchen-appliances",
            "name": "Appliances"
          },
          {
            "slug": "sub-tools-kitchen-tongs",
            "name": "Tongs"
          },
          {
            "slug": "sub-tools-kitchen-strainers",
            "name": "Strainers"
          },
          {
            "slug": "sub-tools-kitchen-utensil-rest",
            "name": "Utensil Rest"
          },
          {
            "slug": "sub-tools-kitchen-peelers",
            "name": "Peelers"
          },
          {
            "slug": "sub-tools-kitchen-juice-squeezers",
            "name": "Juice Squeezers"
          },
          {
            "slug": "sub-tools-kitchen-slicers-graters-cheese",
            "name": "Slicers & Graters-Cheese"
          },
          {
            "slug": "sub-tools-kitchen-whisks",
            "name": "Whisks"
          },
          {
            "slug": "sub-tools-kitchen-coffee-grinders",
            "name": "Coffee Grinders"
          },
          {
            "slug": "sub-tools-kitchen-cookie-cutters-presses",
            "name": "Cookie Cutters & Presses"
          },
          {
            "slug": "sub-tools-kitchen-crumbers",
            "name": "Crumbers"
          },
          {
            "slug": "sub-tools-kitchen-ladles",
            "name": "Ladles"
          },
          {
            "slug": "sub-tools-kitchen-pie-cake-servers",
            "name": "Pie & Cake Servers"
          },
          {
            "slug": "sub-tools-kitchen-egg-separators",
            "name": "Egg Separators"
          },
          {
            "slug": "sub-tools-kitchen-rolling-pins",
            "name": "Rolling Pins"
          }
        ]
      },
      {
        "slug": "cat-towels",
        "name": "Towels",
        "children": [
          {
            "slug": "sub-towels-sports",
            "name": "Sports"
          },
          {
            "slug": "sub-towels-beach",
            "name": "Beach"
          },
          {
            "slug": "sub-towels-general",
            "name": "General"
          },
          {
            "slug": "sub-towels-hand",
            "name": "Hand"
          },
          {
            "slug": "sub-towels-bath",
            "name": "Bath"
          },
          {
            "slug": "sub-towels-kitchen",
            "name": "Kitchen"
          },
          {
            "slug": "sub-towels-wrap-around",
            "name": "Wrap Around"
          }
        ]
      }
    ]
  },
  {
    "slug": "events-giveaways",
    "name": "Events & Giveaways",
    "children": [
      {
        "slug": "cat-decals",
        "name": "Decals & Stickers",
        "children": [
          {
            "slug": "sub-decals-vinyl",
            "name": "Vinyl"
          },
          {
            "slug": "sub-decals-general",
            "name": "General"
          },
          {
            "slug": "sub-decals-electrostatic",
            "name": "Electrostatic"
          },
          {
            "slug": "sub-decals-parking-permit",
            "name": "Parking Permit"
          },
          {
            "slug": "sub-decals-mylar",
            "name": "Mylar"
          },
          {
            "slug": "sub-decals-foil",
            "name": "Foil"
          },
          {
            "slug": "sub-decals-glitter",
            "name": "Glitter"
          },
          {
            "slug": "sub-decals-metal",
            "name": "Metal"
          }
        ]
      },
      {
        "slug": "cat-flags",
        "name": "Flags",
        "children": [
          {
            "slug": "sub-flags-horizontal",
            "name": "Horizontal"
          },
          {
            "slug": "sub-flags-auto-window",
            "name": "Auto Window"
          },
          {
            "slug": "sub-flags-table-top",
            "name": "Table Top"
          },
          {
            "slug": "sub-flags-vertical",
            "name": "Vertical"
          },
          {
            "slug": "sub-flags-foreign",
            "name": "Foreign"
          },
          {
            "slug": "sub-flags-state-territorial",
            "name": "State/Territorial"
          },
          {
            "slug": "sub-flags-united-states",
            "name": "United States"
          },
          {
            "slug": "sub-flags-general",
            "name": "General"
          },
          {
            "slug": "sub-flags-military",
            "name": "Military"
          },
          {
            "slug": "sub-flags-auto-dealer",
            "name": "Auto Dealer"
          },
          {
            "slug": "sub-flags-danger-emergency",
            "name": "Danger/Emergency"
          }
        ]
      },
      {
        "slug": "cat-candy",
        "name": "Candy",
        "children": [
          {
            "slug": "sub-candy-chocolate",
            "name": "Chocolate"
          },
          {
            "slug": "sub-candy-general",
            "name": "General"
          },
          {
            "slug": "sub-candy-mints",
            "name": "Mints"
          },
          {
            "slug": "sub-candy-jelly-beans",
            "name": "Jelly Beans"
          },
          {
            "slug": "sub-candy-hard-type",
            "name": "Hard Type"
          },
          {
            "slug": "sub-candy-chewing-gum",
            "name": "Chewing Gum"
          },
          {
            "slug": "sub-candy-salt-water-taffy",
            "name": "Salt Water Taffy"
          },
          {
            "slug": "sub-candy-lollipops",
            "name": "Lollipops"
          },
          {
            "slug": "sub-candy-candy-canes",
            "name": "Candy Canes"
          }
        ]
      },
      {
        "slug": "cat-magnets",
        "name": "Magnets",
        "children": [
          {
            "slug": "sub-magnets-memo-holder",
            "name": "Memo Holder"
          },
          {
            "slug": "sub-magnets-industrial-toy",
            "name": "Industrial/Toy"
          }
        ]
      },
      {
        "slug": "cat-food-gifts",
        "name": "Food Gifts",
        "children": [
          {
            "slug": "sub-food-gifts-general",
            "name": "General"
          },
          {
            "slug": "sub-food-gifts-nuts",
            "name": "Nuts"
          },
          {
            "slug": "sub-food-gifts-bakery-items",
            "name": "Bakery Items"
          },
          {
            "slug": "sub-food-gifts-gourmet",
            "name": "Gourmet"
          },
          {
            "slug": "sub-food-gifts-assortments",
            "name": "Assortments"
          },
          {
            "slug": "sub-food-gifts-snack-or-trail-mixes",
            "name": "Snack or Trail Mixes"
          },
          {
            "slug": "sub-food-gifts-pretzels",
            "name": "Pretzels"
          },
          {
            "slug": "sub-food-gifts-hot-chocolate",
            "name": "Hot Chocolate"
          },
          {
            "slug": "sub-food-gifts-popcorn",
            "name": "Popcorn"
          },
          {
            "slug": "sub-food-gifts-meats-cheeses",
            "name": "Meats & Cheeses"
          },
          {
            "slug": "sub-food-gifts-fruit",
            "name": "Fruit"
          },
          {
            "slug": "sub-food-gifts-crackers",
            "name": "Crackers"
          },
          {
            "slug": "sub-food-gifts-condiments-salsa",
            "name": "Condiments & Salsa"
          },
          {
            "slug": "sub-food-gifts-chips",
            "name": "Chips"
          }
        ]
      },
      {
        "slug": "cat-stress-relievers",
        "name": "Stress Toys",
        "children": [
          {
            "slug": "sub-stress-relievers-general",
            "name": "General"
          },
          {
            "slug": "sub-stress-relievers-balls",
            "name": "Balls"
          }
        ]
      },
      {
        "slug": "cat-signs-displays",
        "name": "Signs & Displays",
        "children": [
          {
            "slug": "sub-signs-displays-general",
            "name": "General"
          },
          {
            "slug": "sub-signs-displays-magnetic",
            "name": "Magnetic"
          },
          {
            "slug": "sub-signs-displays-window",
            "name": "Window"
          },
          {
            "slug": "sub-signs-displays-self-adhesive",
            "name": "Self Adhesive"
          },
          {
            "slug": "sub-signs-displays-kit",
            "name": "Kit"
          },
          {
            "slug": "sub-signs-displays-door-knob",
            "name": "Door Knob"
          },
          {
            "slug": "sub-signs-displays-table-top-tents",
            "name": "Table Top Tents"
          },
          {
            "slug": "sub-signs-displays-point-of-purchase-sale",
            "name": "Point of Purchase/Sale"
          },
          {
            "slug": "sub-signs-displays-bottle-collar",
            "name": "Bottle Collar"
          },
          {
            "slug": "sub-signs-displays-exhibit-booths",
            "name": "Exhibit Booths"
          },
          {
            "slug": "sub-signs-displays-realty",
            "name": "Realty"
          },
          {
            "slug": "sub-signs-displays-on-board-type",
            "name": "On Board Type"
          },
          {
            "slug": "sub-signs-displays-neon",
            "name": "Neon"
          },
          {
            "slug": "sub-signs-displays-handicapped",
            "name": "Handicapped"
          },
          {
            "slug": "sub-signs-displays-with-clock",
            "name": "With Clock"
          },
          {
            "slug": "sub-signs-displays-electric",
            "name": "Electric"
          }
        ]
      },
      {
        "slug": "cat-kits",
        "name": "Kits",
        "children": [
          {
            "slug": "sub-kits-general",
            "name": "General"
          },
          {
            "slug": "sub-kits-first-aid",
            "name": "First Aid"
          },
          {
            "slug": "sub-kits-travel",
            "name": "Travel"
          },
          {
            "slug": "sub-kits-lunch",
            "name": "Lunch"
          },
          {
            "slug": "sub-kits-ppe",
            "name": "PPE"
          },
          {
            "slug": "sub-kits-grooming",
            "name": "Grooming"
          },
          {
            "slug": "sub-kits-desk-accessories",
            "name": "Desk Accessories"
          },
          {
            "slug": "sub-kits-emergency-preparedness",
            "name": "Emergency Preparedness"
          },
          {
            "slug": "sub-kits-auto",
            "name": "Auto"
          },
          {
            "slug": "sub-kits-repair",
            "name": "Repair"
          },
          {
            "slug": "sub-kits-identification",
            "name": "Identification"
          },
          {
            "slug": "sub-kits-hobby",
            "name": "Hobby"
          }
        ]
      },
      {
        "slug": "cat-lanyards",
        "name": "Lanyards"
      },
      {
        "slug": "cat-banners",
        "name": "Banners",
        "children": [
          {
            "slug": "sub-banners-general",
            "name": "General"
          },
          {
            "slug": "sub-banners-buntings",
            "name": "Buntings"
          },
          {
            "slug": "sub-banners-lightpoles",
            "name": "Lightpoles"
          }
        ]
      },
      {
        "slug": "cat-badge-holders",
        "name": "Badge Holders",
        "children": [
          {
            "slug": "sub-badge-holders-retractable",
            "name": "Retractable"
          },
          {
            "slug": "sub-badge-holders-convention-type",
            "name": "Convention Type"
          },
          {
            "slug": "sub-badge-holders-general",
            "name": "General"
          }
        ]
      },
      {
        "slug": "cat-gift-sets",
        "name": "Gift Sets"
      }
    ]
  }
];

/** ASI ContextPath -> curated leaf slug. */
export const sourceMap: SourceMap = {
  "Awards-Corporate": "sub-awards-corporate",
  "Awards-Crystal": "sub-awards-crystal",
  "Awards-Glass": "sub-awards-glass",
  "Awards-General": "sub-awards-general",
  "Awards-Acrylic": "sub-awards-acrylic",
  "Awards-Sculptures & Figurines": "sub-awards-sculptures-figurines",
  "Awards-Recognition Plaques": "sub-awards-recognition-plaques",
  "Awards-Sports": "sub-awards-sports",
  "Awards-Clocks": "sub-awards-clocks",
  "Awards-Stands & Bases": "sub-awards-stands-bases",
  "Awards-Trophies": "sub-awards-trophies",
  "Awards-Custom": "sub-awards-custom",
  "Awards-Loving Cups": "sub-awards-loving-cups",
  "Awards-Embedments": "sub-awards-embedments",
  "Bags-General": "sub-bags-general",
  "Bags-Drawstring": "sub-bags-drawstring",
  "Bags-Shopping": "sub-bags-shopping",
  "Bags-Lunch": "sub-bags-lunch",
  "Bags-Fanny/Hip/Waist": "sub-bags-fanny-hip-waist",
  "Bags-Bottle": "sub-bags-bottle",
  "Bags-Crossbody and Sling": "sub-bags-crossbody-and-sling",
  "Bags-Food": "sub-bags-food",
  "Bags-Shoe": "sub-bags-shoe",
  "Bags-Resealable/Reclosable": "sub-bags-resealable-reclosable",
  "Bags-Laundry": "sub-bags-laundry",
  "Bags-Leather": "sub-bags-leather",
  "Bags-Litter": "sub-bags-litter",
  "Bags-Diaper": "sub-bags-diaper",
  "Glasses-Drinking-Sets": "sub-glasses-drinking-sets",
  "Glasses-Drinking-Insulated": "sub-glasses-drinking-insulated",
  "Glasses-Drinking-Tumbler": "sub-glasses-drinking-tumbler",
  "Glasses-Drinking-With Lid & Straw": "sub-glasses-drinking-with-lid-straw",
  "Glasses-Drinking-On The Rocks": "sub-glasses-drinking-on-the-rocks",
  "Glasses-Drinking-General": "sub-glasses-drinking-general",
  "Glasses-Drinking-Champagne": "sub-glasses-drinking-champagne",
  "Glasses-Drinking-Pilsner": "sub-glasses-drinking-pilsner",
  "Glasses-Drinking-Highball": "sub-glasses-drinking-highball",
  "Glasses-Drinking-Margarita": "sub-glasses-drinking-margarita",
  "Glasses-Drinking-Beer Jars": "sub-glasses-drinking-beer-jars",
  "Glasses-Drinking-Old Fashioned": "sub-glasses-drinking-old-fashioned",
  "Glasses-Drinking-Martini": "sub-glasses-drinking-martini",
  "Glasses-Drinking-Goblets": "sub-glasses-drinking-goblets",
  "Glasses-Drinking-Hurricane": "sub-glasses-drinking-hurricane",
  "Glasses-Drinking-Lighted": "sub-glasses-drinking-lighted",
  "Pens-Ballpoint-Plunger Action": "sub-pens-ballpoint-plunger-action",
  "Pens-Ballpoint-Stylus": "sub-pens-ballpoint-stylus",
  "Pens-Ballpoint-With Grip Section": "sub-pens-ballpoint-with-grip-section",
  "Pens-Ballpoint-Twist Action": "sub-pens-ballpoint-twist-action",
  "Pens-General": "sub-pens-general",
  "Pens-Ballpoint-General": "sub-pens-ballpoint-general",
  "Pens-Ballpoint-Roller Ball": "sub-pens-ballpoint-roller-ball",
  "Pens-Ballpoint-Gel Ink": "sub-pens-ballpoint-gel-ink",
  "Pens-Ballpoint-Transparent Barrel or Cap": "sub-pens-ballpoint-transparent-barrel-or-cap",
  "Pens-Ballpoint-With Light": "sub-pens-ballpoint-with-light",
  "Pens-Ballpoint-With Highlighter": "sub-pens-ballpoint-with-highlighter",
  "Pens-Ballpoint-Suede or Matte Finish": "sub-pens-ballpoint-suede-or-matte-finish",
  "Pens-Ballpoint-Wide Body": "sub-pens-ballpoint-wide-body",
  "Pens-Ballpoint-Clip Action": "sub-pens-ballpoint-clip-action",
  "Pens-Ballpoint-Lacquered Finish": "sub-pens-ballpoint-lacquered-finish",
  "Pens-Ballpoint-Multi-Color": "sub-pens-ballpoint-multi-color",
  "Pens-Ballpoint-Stick": "sub-pens-ballpoint-stick",
  "Pens-Fountain": "sub-pens-fountain",
  "Pens-Ballpoint-Cap Action": "sub-pens-ballpoint-cap-action",
  "Pens-Ballpoint-Triangular": "sub-pens-ballpoint-triangular",
  "Pens-Ballpoint-With Neck Chain/Rope": "sub-pens-ballpoint-with-neck-chain-rope",
  "Tote Bags-General": "sub-tote-bags-general",
  "Tote Bags-Non Woven": "sub-tote-bags-non-woven",
  "Tote Bags-Canvas": "sub-tote-bags-canvas",
  "Tote Bags-Grocery": "sub-tote-bags-grocery",
  "Tote Bags-Insulated": "sub-tote-bags-insulated",
  "Tote Bags-Jute": "sub-tote-bags-jute",
  "Tote Bags-Beach": "sub-tote-bags-beach",
  "Tote Bags-Boat": "sub-tote-bags-boat",
  "Decals-Vinyl": "sub-decals-vinyl",
  "Decals-General": "sub-decals-general",
  "Decals-Electrostatic": "sub-decals-electrostatic",
  "Decals-Parking Permit": "sub-decals-parking-permit",
  "Decals-Mylar": "sub-decals-mylar",
  "Decals-Foil": "sub-decals-foil",
  "Decals-Glitter": "sub-decals-glitter",
  "Decals-Metal": "sub-decals-metal",
  "Key Chains-General": "sub-key-chains-general",
  "Key Chains-Metal": "sub-key-chains-metal",
  "Key Chains-With Bottle or Can Opener": "sub-key-chains-with-bottle-or-can-opener",
  "Key Chains-With Flashlight and/or Whistle": "sub-key-chains-with-flashlight-and-or-whistle",
  "Key Chains-Plastic": "sub-key-chains-plastic",
  "Key Chains-With Carabiner": "sub-key-chains-with-carabiner",
  "Key Chains-Floating": "sub-key-chains-floating",
  "Key Chains-Leather": "sub-key-chains-leather",
  "Key Chains-With Tools": "sub-key-chains-with-tools",
  "Key Chains-Vinyl": "sub-key-chains-vinyl",
  "Key Chains-Flexible Loop": "sub-key-chains-flexible-loop",
  "Key Chains-Stock or ID": "sub-key-chains-stock-or-id",
  "BAR ACCESSORIES": "cat-bar-accessories",
  "PERFORMANCE APPAREL": "cat-performance-apparel",
  "Bottles-Insulated": "sub-bottles-insulated",
  "Bottles-Sport Type": "sub-bottles-sport-type",
  "Bottles-General": "sub-bottles-general",
  "Bottles-Collapsible": "sub-bottles-collapsible",
  "Bottles-Spray": "sub-bottles-spray",
  "Bottles-Baby": "sub-bottles-baby",
  "Backpacks-General": "sub-backpacks-general",
  "Backpacks-Laptop": "sub-backpacks-laptop",
  "Backpacks-Drawstring": "sub-backpacks-drawstring",
  "Backpacks-School": "sub-backpacks-school",
  "Flags-Horizontal": "sub-flags-horizontal",
  "Flags-Auto Window": "sub-flags-auto-window",
  "Flags-Table Top": "sub-flags-table-top",
  "Flags-Vertical": "sub-flags-vertical",
  "Flags-Foreign": "sub-flags-foreign",
  "Flags-State/Territorial": "sub-flags-state-territorial",
  "Flags-United States": "sub-flags-united-states",
  "Flags-General": "sub-flags-general",
  "Flags-Military": "sub-flags-military",
  "Flags-Auto Dealer": "sub-flags-auto-dealer",
  "Flags-Danger/Emergency": "sub-flags-danger-emergency",
  "TRAVEL MUGS/CUPS": "cat-travel-mugs-cups",
  "Fans-General": "sub-fans-general",
  "Fans-USB": "sub-fans-usb",
  "Mobile Accessories-Stands & Holders": "sub-mobile-accessories-stands-holders",
  "Mobile Accessories-General": "sub-mobile-accessories-general",
  "Mobile Accessories-Cables & Cords": "sub-mobile-accessories-cables-cords",
  "Mobile Accessories-Cell Phone Wallets": "sub-mobile-accessories-cell-phone-wallets",
  "Mobile Accessories-Cell Phone Cases": "sub-mobile-accessories-cell-phone-cases",
  "Mobile Accessories-Selfie Lights": "sub-mobile-accessories-selfie-lights",
  "Mobile Accessories-Selfie Sticks": "sub-mobile-accessories-selfie-sticks",
  "Candy-Chocolate": "sub-candy-chocolate",
  "Candy-General": "sub-candy-general",
  "Candy-Mints": "sub-candy-mints",
  "Candy-Jelly Beans": "sub-candy-jelly-beans",
  "Candy-Hard Type": "sub-candy-hard-type",
  "Candy-Chewing Gum": "sub-candy-chewing-gum",
  "Candy-Salt Water Taffy": "sub-candy-salt-water-taffy",
  "Candy-Lollipops": "sub-candy-lollipops",
  "Candy-Candy Canes": "sub-candy-candy-canes",
  "Caps & Hats-General": "sub-caps-hats-general",
  "Caps & Hats-Beanie": "sub-caps-hats-beanie",
  "Caps & Hats-Golf-General": "sub-caps-hats-golf-general",
  "Caps & Hats-Visors": "sub-caps-hats-visors",
  "Caps & Hats-Aussie": "sub-caps-hats-aussie",
  "Caps & Hats-Santa": "sub-caps-hats-santa",
  "Caps & Hats-Straw": "sub-caps-hats-straw",
  "Caps & Hats-Construction": "sub-caps-hats-construction",
  "Caps & Hats-With Ear Protection": "sub-caps-hats-with-ear-protection",
  "Caps & Hats-Swimming": "sub-caps-hats-swimming",
  "Caps & Hats-Fedora": "sub-caps-hats-fedora",
  "Caps & Hats-Chef's": "sub-caps-hats-chef-s",
  "Caps & Hats-Sombrero": "sub-caps-hats-sombrero",
  "Caps & Hats-Derby": "sub-caps-hats-derby",
  "Caps & Hats-Yarmulkas": "sub-caps-hats-yarmulkas",
  "Battery Rechargers & Adaptors-Power Banks": "sub-battery-rechargers-adaptors-power-banks",
  "Battery Rechargers & Adaptors-Wireless QI Charger": "sub-battery-rechargers-adaptors-wireless-qi-charger",
  "Battery Rechargers & Adaptors-General": "sub-battery-rechargers-adaptors-general",
  "Jackets-General": "sub-jackets-general",
  "Jackets-Pullover": "sub-jackets-pullover",
  "Jackets-Windbreaker": "sub-jackets-windbreaker",
  "Jackets-Work": "sub-jackets-work",
  "Jackets-Parka": "sub-jackets-parka",
  "Jackets-In Pouch": "sub-jackets-in-pouch",
  "Jackets-Bomber": "sub-jackets-bomber",
  "Jackets-Blazer": "sub-jackets-blazer",
  "Jackets-Varsity/Letterman": "sub-jackets-varsity-letterman",
  "Jackets-Baseball/Coach": "sub-jackets-baseball-coach",
  "Mugs & Steins-Ceramic": "sub-mugs-steins-ceramic",
  "Mugs & Steins-Insulated": "sub-mugs-steins-insulated",
  "Mugs & Steins-Metal": "sub-mugs-steins-metal",
  "Mugs & Steins-Glass": "sub-mugs-steins-glass",
  "Mugs & Steins-General": "sub-mugs-steins-general",
  "Mugs & Steins-Plastic": "sub-mugs-steins-plastic",
  "Mugs & Steins-Porcelain": "sub-mugs-steins-porcelain",
  "Mugs & Steins-Aluminum": "sub-mugs-steins-aluminum",
  "Mugs & Steins-Irish Coffee": "sub-mugs-steins-irish-coffee",
  "Mugs & Steins-Soup Type": "sub-mugs-steins-soup-type",
  "COOLERS": "cat-coolers",
  "Magnets-Memo Holder": "sub-magnets-memo-holder",
  "Magnets-Industrial/Toy": "sub-magnets-industrial-toy",
  "T-Shirts-Unisex": "sub-t-shirts-unisex",
  "T-Shirts-Womens": "sub-t-shirts-womens",
  "T-Shirts-Mens": "sub-t-shirts-mens",
  "T-Shirts-Children": "sub-t-shirts-children",
  "Golf/Polo Shirts-Mens": "sub-golf-polo-shirts-mens",
  "Golf/Polo Shirts-Womens": "sub-golf-polo-shirts-womens",
  "Golf/Polo Shirts-Unisex": "sub-golf-polo-shirts-unisex",
  "Golf/Polo Shirts-Childrens": "sub-golf-polo-shirts-childrens",
  "Food Gifts-General": "sub-food-gifts-general",
  "Food Gifts-Nuts": "sub-food-gifts-nuts",
  "Food Gifts-Bakery Items": "sub-food-gifts-bakery-items",
  "Food Gifts-Gourmet": "sub-food-gifts-gourmet",
  "Food Gifts-Assortments": "sub-food-gifts-assortments",
  "Food Gifts-Snack or Trail Mixes": "sub-food-gifts-snack-or-trail-mixes",
  "Food Gifts-Pretzels": "sub-food-gifts-pretzels",
  "Food Gifts-Hot Chocolate": "sub-food-gifts-hot-chocolate",
  "Food Gifts-Popcorn": "sub-food-gifts-popcorn",
  "Food Gifts-Meats & Cheeses": "sub-food-gifts-meats-cheeses",
  "Food Gifts-Fruit": "sub-food-gifts-fruit",
  "Food Gifts-Crackers": "sub-food-gifts-crackers",
  "Food Gifts-Condiments & Salsa": "sub-food-gifts-condiments-salsa",
  "Food Gifts-Chips": "sub-food-gifts-chips",
  "WINE ACCESSORIES": "cat-wine-accessories",
  "Stress Relievers-General": "sub-stress-relievers-general",
  "Stress Relievers-Balls": "sub-stress-relievers-balls",
  "Shirts-Womens": "sub-shirts-womens",
  "Shirts-Tank Tops/Muscle": "sub-shirts-tank-tops-muscle",
  "Shirts-Unisex": "sub-shirts-unisex",
  "Shirts-Mens": "sub-shirts-mens",
  "Shirts-Athletic": "sub-shirts-athletic",
  "Shirts-Dress": "sub-shirts-dress",
  "Shirts-Childrens": "sub-shirts-childrens",
  "Shirts-General": "sub-shirts-general",
  "Shirts-Henley": "sub-shirts-henley",
  "Shirts-Camp": "sub-shirts-camp",
  "Shirts-Denim": "sub-shirts-denim",
  "Shirts-Wind Shirts": "sub-shirts-wind-shirts",
  "Shirts-Turtleneck": "sub-shirts-turtleneck",
  "Sweat Shirts-Unisex": "sub-sweat-shirts-unisex",
  "Sweat Shirts-Womens": "sub-sweat-shirts-womens",
  "Sweat Shirts-Mens": "sub-sweat-shirts-mens",
  "Sweat Shirts-Children": "sub-sweat-shirts-children",
  "NOTEBOOKS": "cat-notebooks",
  "Signs & Displays-General": "sub-signs-displays-general",
  "Signs & Displays-Magnetic": "sub-signs-displays-magnetic",
  "Signs & Displays-Window": "sub-signs-displays-window",
  "Signs & Displays-Self Adhesive": "sub-signs-displays-self-adhesive",
  "Signs & Displays-Kit": "sub-signs-displays-kit",
  "Signs & Displays-Door Knob": "sub-signs-displays-door-knob",
  "Signs & Displays-Table Top Tents": "sub-signs-displays-table-top-tents",
  "Signs & Displays-Point of Purchase/Sale": "sub-signs-displays-point-of-purchase-sale",
  "Signs & Displays-Bottle Collar": "sub-signs-displays-bottle-collar",
  "Signs & Displays-Exhibit Booths": "sub-signs-displays-exhibit-booths",
  "Signs & Displays-Realty": "sub-signs-displays-realty",
  "Signs & Displays-On Board Type": "sub-signs-displays-on-board-type",
  "Signs & Displays-Neon": "sub-signs-displays-neon",
  "Signs & Displays-Handicapped": "sub-signs-displays-handicapped",
  "Signs & Displays-With Clock": "sub-signs-displays-with-clock",
  "Signs & Displays-Electric": "sub-signs-displays-electric",
  "Baseball Caps-Six Panel": "sub-baseball-caps-six-panel",
  "Baseball Caps-with Mesh": "sub-baseball-caps-with-mesh",
  "Baseball Caps-General": "sub-baseball-caps-general",
  "Baseball Caps-Five Panels": "sub-baseball-caps-five-panels",
  "Baseball Caps-Camouflage": "sub-baseball-caps-camouflage",
  "Baseball Caps-Sandwich Bill": "sub-baseball-caps-sandwich-bill",
  "Openers-Bottle": "sub-openers-bottle",
  "Openers-Can": "sub-openers-can",
  "Openers-General": "sub-openers-general",
  "Openers-Touchless": "sub-openers-touchless",
  "Openers-Jar": "sub-openers-jar",
  "JOURNALS & DIARIES": "cat-journals-diaries",
  "Pouches-General": "sub-pouches-general",
  "Pouches-Jewelry": "sub-pouches-jewelry",
  "USB/FLASH DRIVES": "cat-usb-flash-drives",
  "Kits-General": "sub-kits-general",
  "Kits-First Aid": "sub-kits-first-aid",
  "Kits-Travel": "sub-kits-travel",
  "Kits-Lunch": "sub-kits-lunch",
  "Kits-PPE": "sub-kits-ppe",
  "Kits-Grooming": "sub-kits-grooming",
  "Kits-Desk Accessories": "sub-kits-desk-accessories",
  "Kits-Emergency Preparedness": "sub-kits-emergency-preparedness",
  "Kits-Auto": "sub-kits-auto",
  "Kits-Repair": "sub-kits-repair",
  "Kits-Identification": "sub-kits-identification",
  "Kits-Hobby": "sub-kits-hobby",
  "Uniforms-Sports": "sub-uniforms-sports",
  "Uniforms-Work Clothes": "sub-uniforms-work-clothes",
  "Uniforms-Restaurant/Hospitality": "sub-uniforms-restaurant-hospitality",
  "Uniforms-General": "sub-uniforms-general",
  "Uniforms-Lab Coats": "sub-uniforms-lab-coats",
  "Uniforms-Scrubs": "sub-uniforms-scrubs",
  "LANYARDS": "cat-lanyards",
  "Beverage Holders-Sleeve": "sub-beverage-holders-sleeve",
  "Beverage Holders-General": "sub-beverage-holders-general",
  "Beverage Holders-Wrap Around": "sub-beverage-holders-wrap-around",
  "Banners-General": "sub-banners-general",
  "Banners-Buntings": "sub-banners-buntings",
  "Banners-Lightpoles": "sub-banners-lightpoles",
  "Golf Accessories-Sets": "sub-golf-accessories-sets",
  "Golf Accessories-General": "sub-golf-accessories-general",
  "Golf Accessories-Divot Fixer": "sub-golf-accessories-divot-fixer",
  "Golf Accessories-Ball Markers": "sub-golf-accessories-ball-markers",
  "Golf Accessories-Gloves": "sub-golf-accessories-gloves",
  "Golf Accessories-Ditty Bags": "sub-golf-accessories-ditty-bags",
  "Golf Accessories-Covers-Club": "sub-golf-accessories-covers-club",
  "Golf Accessories-Bag Tags": "sub-golf-accessories-bag-tags",
  "Golf Accessories-Club Cleaners": "sub-golf-accessories-club-cleaners",
  "Golf Accessories-Green Readers & Rangefinders": "sub-golf-accessories-green-readers-rangefinders",
  "Golf Accessories-Ball Cleaners": "sub-golf-accessories-ball-cleaners",
  "Golf Accessories-Putting Cups/Greens": "sub-golf-accessories-putting-cups-greens",
  "Golf Accessories-Covers-Bag": "sub-golf-accessories-covers-bag",
  "Golf Accessories-Ball Retrievers": "sub-golf-accessories-ball-retrievers",
  "Golf Accessories-Scoring Devices": "sub-golf-accessories-scoring-devices",
  "SUNGLASSES": "cat-sunglasses",
  "Calendars-Wall-General": "sub-calendars-wall-general",
  "Calendars-Art": "sub-calendars-art",
  "Calendars-Magnetic": "sub-calendars-magnetic",
  "Calendars-General": "sub-calendars-general",
  "Calendars-Year On A Page": "sub-calendars-year-on-a-page",
  "Calendars-Desk-Monthly": "sub-calendars-desk-monthly",
  "Calendars-Self-Adhering": "sub-calendars-self-adhering",
  "Calendars-Commercial": "sub-calendars-commercial",
  "Calendars-Executive": "sub-calendars-executive",
  "Calendars-Religious": "sub-calendars-religious",
  "Calendars-Wall-Pocketed": "sub-calendars-wall-pocketed",
  "Calendars-Daily Date": "sub-calendars-daily-date",
  "Calendars-Almanac": "sub-calendars-almanac",
  "Calendars-Custom Made": "sub-calendars-custom-made",
  "Calendars-Perpetual": "sub-calendars-perpetual",
  "Calendars-Year-On-A-Page-Pocket": "sub-calendars-year-on-a-page-pocket",
  "Badge Holders-Retractable": "sub-badge-holders-retractable",
  "Badge Holders-Convention Type": "sub-badge-holders-convention-type",
  "Badge Holders-General": "sub-badge-holders-general",
  "GIFT SETS": "cat-gift-sets",
  "Sports Equipment & Access.-General": "sub-sports-equipment-access-general",
  "Sports Equipment & Access.-Baseball/Softball": "sub-sports-equipment-access-baseball-softball",
  "Sports Equipment & Access.-Pickleball": "sub-sports-equipment-access-pickleball",
  "Sports Equipment & Access.-Hockey": "sub-sports-equipment-access-hockey",
  "Sports Equipment & Access.-Fishing & Hunting": "sub-sports-equipment-access-fishing-hunting",
  "Sports Equipment & Access.-Tennis": "sub-sports-equipment-access-tennis",
  "Sports Equipment & Access.-Jogging": "sub-sports-equipment-access-jogging",
  "Sports Equipment & Access.-Capsules": "sub-sports-equipment-access-capsules",
  "Sports Equipment & Access.-Skiing": "sub-sports-equipment-access-skiing",
  "Sports Equipment & Access.-Skating": "sub-sports-equipment-access-skating",
  "Sports Equipment & Access.-Weight Lifting": "sub-sports-equipment-access-weight-lifting",
  "COASTERS & COASTER SETS": "cat-coasters-coaster-sets",
  "Tools-Kitchen-General": "sub-tools-kitchen-general",
  "Tools-Kitchen-Sets": "sub-tools-kitchen-sets",
  "Tools-Kitchen-Spatulas/Spreaders": "sub-tools-kitchen-spatulas-spreaders",
  "Tools-Kitchen-Coffee Makers": "sub-tools-kitchen-coffee-makers",
  "Tools-Kitchen-Pizza Accessories": "sub-tools-kitchen-pizza-accessories",
  "Tools-Kitchen-Appliances": "sub-tools-kitchen-appliances",
  "Tools-Kitchen-Tongs": "sub-tools-kitchen-tongs",
  "Tools-Kitchen-Strainers": "sub-tools-kitchen-strainers",
  "Tools-Kitchen-Utensil Rest": "sub-tools-kitchen-utensil-rest",
  "Tools-Kitchen-Peelers": "sub-tools-kitchen-peelers",
  "Tools-Kitchen-Juice Squeezers": "sub-tools-kitchen-juice-squeezers",
  "Tools-Kitchen-Slicers & Graters-Cheese": "sub-tools-kitchen-slicers-graters-cheese",
  "Tools-Kitchen-Whisks": "sub-tools-kitchen-whisks",
  "Tools-Kitchen-Coffee Grinders": "sub-tools-kitchen-coffee-grinders",
  "Tools-Kitchen-Cookie Cutters & Presses": "sub-tools-kitchen-cookie-cutters-presses",
  "Tools-Kitchen-Crumbers": "sub-tools-kitchen-crumbers",
  "Tools-Kitchen-Ladles": "sub-tools-kitchen-ladles",
  "Tools-Kitchen-Pie & Cake Servers": "sub-tools-kitchen-pie-cake-servers",
  "Tools-Kitchen-Egg Separators": "sub-tools-kitchen-egg-separators",
  "Tools-Kitchen-Rolling Pins": "sub-tools-kitchen-rolling-pins",
  "Towels-Sports": "sub-towels-sports",
  "Towels-Beach": "sub-towels-beach",
  "Towels-General": "sub-towels-general",
  "Towels-Hand": "sub-towels-hand",
  "Towels-Bath": "sub-towels-bath",
  "Towels-Kitchen": "sub-towels-kitchen",
  "Towels-Wrap Around": "sub-towels-wrap-around"
};
